---
services:
  db:
    image: vishalgogula123/firstrepo:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1

  appimage:
    image: vishalgogula123/firstrepo:appimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 3


  auth_service:
    image: vishalgogula123/firstrepo:auth_service
    ports:
      - "5001:5001"
    deploy:
      replicas: 3


  borrow_service:
    image: vishalgogula123/firstrepo:borrow_service
    ports:
      - "5003:5003"
    deploy:
      replicas: 3

  book_service:
    image: vishalgogula123/firstrepo:book_service
    ports:
      - "5002:5002"
    deploy:
      replicas: 3


